AWSTemplateFormatVersion: 2010-09-09
Description: To create ECS Clusters and Service.

Parameters:
  ResourcePrefix:
    Description: Resource prefix that will be used for all resource names 
    Type: String
  EnvironmentName:
    Description: An environment name that will be used for resource names
    Type: String
  ClusterName:
    Description: Cluster Name
    Type: String

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ResourcePrefix}-${EnvironmentName}-${ClusterName}
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${EnvironmentName}-${ClusterName}
          
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ResourcePrefix}-${EnvironmentName}-ECSTaskExecutionRole'
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ResourcePrefix}-${EnvironmentName}-ECSTaskExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:CreateLogGroup'
                Resource: '*'
          
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ResourcePrefix}-${EnvironmentName}-ECSTaskRole'
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ResourcePrefix}-${EnvironmentName}-ECSTaskRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'lambda:InvokeFunction'
                  - 'sns:Publish'
                  - 'sqs:SendMessage'
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:UpdateTable'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'secretsmanager:GetSecretValue'
                  - 'dynamodb:Scan'
                Resource: '*'
           
  SSMTaskExecutionRole:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Type: String
      Description: !Sub 'Task Executrion Role ARN '
      Value: !GetAtt ECSTaskExecutionRole.Arn
      Name: !Sub '/${ResourcePrefix}/${EnvironmentName}/${ClusterName}/ExecutionRole/ARN'

  SSMforECSClusterName:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Type: String
      Description: !Sub 'Name of ${ClusterName} ECS Cluster'
      Value: !Sub ${ResourcePrefix}-${EnvironmentName}-${ClusterName}
      Name: !Sub '/${ResourcePrefix}/${EnvironmentName}/${ClusterName}/name'
      Tags:
        Name: !Sub /${ResourcePrefix}/${EnvironmentName}/${ClusterName}/name

  SSMforECSClusterArn:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Type: String
      Description: !Sub 'ARN of ${ClusterName} ECS Cluster'
      Value: !GetAtt ECSCluster.Arn
      Name: !Sub '/${ResourcePrefix}/${EnvironmentName}/cluster/${ClusterName}/arn'

  SSMTaskRole:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Type: String
      Description: !Sub 'Task Role ARN '
      Value: !GetAtt ECSTaskRole.Arn
      Name: !Sub '/${ResourcePrefix}/${EnvironmentName}/TaskRole/ARN'

Outputs:
  ECSTaskExecutionRoleArn:
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Description: ECS Task Execution Role ARN